#!/bin/bash

## #ddev-generated
## Description: This script reads settings from `ddev ibexa-configurator` and sets up ddev
## Usage: ibexa-setup
## Example: ddev ibexa-setup

source .ddev/commands/host/.utils

[[ -z "$SETTINGS_FILE" ]] && SETTINGS_FILE="./.ddev/.ibexa-instance-settings"
[[ -z "$PROVISION_FILE_GENERAL" ]] && PROVISION_FILE_GENERAL="./.ddev/.ibexa-setup-general-provisioned"
[[ -z "$PROVISION_FILE_SERVICES" ]] && PROVISION_FILE_SERVICES="./.ddev/.ibexa-setup-services-provisioned"
[[ -z "$VERBOSE_INSTALL" ]] && VERBOSE_INSTALL=false

if [[ "$VERBOSE_INSTALL" == false && ! -f "$PROVISION_FILE_GENERAL" && ! -f "$PROVISION_FILE_SERVICES" ]]; then
    clear
fi

if [[ ! -f "$SETTINGS_FILE" ]]; then
    echo "Settings file does not exist, run ddev ibexa-configurator first."
    exit 1
fi

source $SETTINGS_FILE

YAML_TAB="    "

if [[ ! -f "$PROVISION_FILE_GENERAL" ]]; then
    echo "# " >> .env.local
    echo "# dxp-installer generated" >> .env.local
    # Project name
    ddev config --project-name="$DDEV_SITENAME"

    # PHP
    echo "php_version: $PHP_VERSION" > .ddev/config.php.yaml
    echo "👷 Configured PHP version: $PHP_VERSION"

    # NodeJS
    echo "nodejs_version: $NODE_VERSION" > .ddev/config.node.yaml
    echo "👷 Configured Node version: $NODE_VERSION"

    # Web Server
    if [[ "$HTTP_SERVER" == "apache-fpm" ]]
    then
        echo "webserver_type: $HTTP_SERVER" > .ddev/config.http.yaml
    fi
    echo "👷 Configured HTTP server: $HTTP_SERVER"

    # Database
    echo "database:
    type: $DATABASE
    version: $DATABASE_VERSION" > .ddev/config.db.yaml
    echo "👷 Configured Database: $DATABASE:$DATABASE_VERSION"

    # App env
    echo "APP_ENV=$APP_ENV" >> .env.local
    if [[ "$APP_ENV" == "prod" ]]; then
        echo "APP_DEBUG=0" >> .env.local
    else
        echo "APP_DEBUG=1" >> .env.local
    fi
    echo "👷 Configured app environment: $APP_ENV"

    echo "👷 Restarting ddev project to reflect webserver and database changes"

    echo "`date`" > "$PROVISION_FILE_GENERAL"

    verbose_output ddev restart -y
fi

if [[ -f "$PROVISION_FILE_SERVICES" ]]; then
    exit 0
fi

DB_SCHEME=mysql
DB_USER=db
DB_PASS=db
DB_NAME=db
DB_HOST=db
DB_PORT=3306
DB_VERSION=$DATABASE_VERSION
DB_CHARSET=utf8mb4
DB_COLLATION=utf8mb4_unicode_520_ci

ddev dotenv set .ddev/.env --dxp-release="$PRODUCT_VERSION"
verbose_output ddev dotenv set .env.local --app-secret=$(openssl rand -hex 32)

if [[ "$DATABASE" == "mariadb" ]]; then
    DB_VERSION=mariadb-`ddev exec -s db mysql -V | awk '{print $5}' | sed 's/-.*//'`
fi

if [[ "$DATABASE" == "postgres" ]]; then
    DB_PORT=5432
    DB_SCHEME=postgresql
    DB_CHARSET=utf8
    DB_COLLATION=utf8_unicode_ci
fi

echo "# " >> .env.local
echo "# dxp-installer generated" >> .env.local
echo "DATABASE_URL=${DB_SCHEME}://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}?serverVersion=${DB_VERSION}&charset=${DB_CHARSET}" >> .env.local
echo "DATABASE_VERSION=${DB_VERSION}" >> .env.local
echo "DATABASE_CHARSET=${DB_CHARSET}" >> .env.local
echo "DATABASE_COLLATION=${DB_COLLATION}" >> .env.local

echo "👷 Saved database details in .env.local"

if [[ "$HTTP_SERVER" == "apache-fpm" ]]; then
    if ! curl -fsSL \
        "https://raw.githubusercontent.com/ibexa/post-install/$PRODUCT_BRANCH/resources/templates/apache2/vhost.template" \
        -o .ddev/apache/apache-site.conf; then
        echo "⛔️ Could not download template, using local fallback"
        cp .ddev/ibexa-resources/apache2/vhost.template .ddev/apache/apache-site.conf
    else
        echo "👷 Downloaded vhost.template from https://raw.githubusercontent.com/ibexa/post-install/"
    fi

    ddev exec sed -i 's/%HOST_NAME%/${DDEV_PROJECT}.ddev.site/' .ddev/apache/apache-site.conf
    ddev exec sed -i 's/%HOST_ALIAS%/*.ddev.site/' .ddev/apache/apache-site.conf
    ddev exec sed -i 's/%IP_ADDRESS%/*/' .ddev/apache/apache-site.conf
    ddev exec sed -i 's/%PORT%/80/' .ddev/apache/apache-site.conf
    ddev exec "sed -i 's|%BASEDIR%|/var/www/html|' .ddev/apache/apache-site.conf"
    ddev exec sed -i 's/%BODY_SIZE_LIMIT%/0/' .ddev/apache/apache-site.conf
    ddev exec sed -i 's/%TIMEOUT%/0/' .ddev/apache/apache-site.conf
    ddev exec "sed -i 's|%FASTCGI_PASS%|unix:/var/run/php-fpm.sock|' .ddev/apache/apache-site.conf"
fi

if [[ "$HTTP_CACHE" == "varnish" ]]; then
    VARNISH_VERSION=7.1
    ddev dotenv set .ddev/.env.varnish --varnish-docker-image=varnish:$VARNISH_VERSION
    ddev add-on get ddev/ddev-varnish

    # fetch vcls from https://raw.githubusercontent.com/ibexa/http-cache
    VCL_SOURCE_DIR="https://raw.githubusercontent.com/ibexa/http-cache/$PRODUCT_BRANCH/docs/varnish/vcl"
    if ! curl -fsSL \
        "$VCL_SOURCE_DIR/parameters.vcl" \
        -o .ddev/varnish/parameters.vcl; then
        echo "⛔️ Could not download parameters.vcl from $VCL_SOURCE_DIR"
    else
        echo "👷 Downloaded parameters.vcl from $VCL_SOURCE_DIR"
    fi

    if ! curl -fsSL \
        "$VCL_SOURCE_DIR/varnish7.vcl" \
        -o .ddev/varnish/default.vcl; then
        echo "⛔️ Could not download varnish7.vcl from $VCL_SOURCE_DIR"
    else
        echo "👷 Downloaded varnish7.vcl from $VCL_SOURCE_DIR"
    fi

    echo "web_environment:
    - TRUSTED_PROXIES=varnish
    - HTTPCACHE_PURGE_TYPE=varnish
    - HTTPCACHE_PURGE_SERVER=http://varnish" > .ddev/config.varnish.yaml

    ddev exec sed -i 's/.host = "127.0.0.1";/.host = "web";/' .ddev/varnish/parameters.vcl
    ddev exec sed -i '/^acl invalidators {$/a \\    "web";' .ddev/varnish/parameters.vcl
    ddev exec sed -i '/^acl debuggers {$/a \\    "0.0.0.0"/0; \/\/ debug from any IP' .ddev/varnish/parameters.vcl
    ddev exec sed -i 's/acl invalidators {/acl invalidators +log {/' .ddev/varnish/parameters.vcl
    ddev exec sed -i 's/acl debuggers {/acl debuggers +log {/' .ddev/varnish/parameters.vcl
fi

echo "👷 Configured HTTP cache: $HTTP_CACHE"

# Memcached
if [[ "$APP_CACHE" == "memcached" ]]; then
    echo "# " >> .env.local
    echo "# dxp-installer generated" >> .env.local
    echo "CACHE_POOL=\"cache.memcached\"" >> .env.local
    echo "CACHE_DSN=\"memcached:11211?weight=33\"" >> .env.local

    verbose_output ddev add-on  get ddev/ddev-memcached
fi

# Redis
if [[ "$APP_CACHE" == "redis" || "$APP_CACHE" == "valkey" ]]; then
    if [[ "$APP_CACHE" == "valkey" ]]; then
      verbose_output ddev dotenv set .ddev/.env.redis --redis-docker-image=valkey/valkey:9.1
    fi
    verbose_output ddev dotenv set .env.local --cache-pool=cache.redis
    verbose_output ddev dotenv set .env.local --cache-dsn=redis:6379

    verbose_output ddev add-on get ddev/ddev-redis

    echo "# dxp-installer generated" > .ddev/redis/redis.conf
    echo "maxmemory 2048mb" >> .ddev/redis/redis.conf
    echo "maxmemory-policy volatile-lfu" >> .ddev/redis/redis.conf
fi

echo "👷 Configured app cache: $APP_CACHE"

# Solr
if [[ "$SEARCH_ENGINE" == "solr" ]]; then
    echo "# " >> .env.local
    echo "# dxp-installer generated" >> .env.local
    echo "SOLR_CORE=collection1" >> .env.local
    echo "SOLR_DSN=http://solr:8983/solr" >> .env.local

    verbose_output ddev add-on get ddev/ddev-solr
    verbose_output ddev dotenv set .ddev/.env.solr --solr-opts="-Dsolr.autoSoftCommit.maxTime=20"
fi

# Elasticsearch
if [[ "$SEARCH_ENGINE" =~ ^elasticsearch ]]; then
    echo "# " >> .env.local
    echo "# dxp-installer generated" >> .env.local
    echo "SEARCH_ENGINE=elasticsearch" >> .env.local
    echo "ELASTICSEARCH_DSN=http://elasticsearch:9200" >> .env.local
    verbose_output ddev add-on  get ddev/ddev-elasticsearch

    if [[ "$PRODUCT_VERSION" =~ ^(~|v)?(5|6)\.0 || "$SEARCH_ENGINE" == "elasticsearch8" ]]; then
        cp .ddev/elasticsearch/docker-compose.elasticsearch8.yaml .ddev/
        verbose_output ddev dotenv set .ddev/.env.elasticsearch --elasticsearch-docker-image=elasticsearch:8.19.0
    else
        cp .ddev/elasticsearch/docker-compose.elasticsearch7.yaml .ddev/
        verbose_output ddev dotenv set .ddev/.env.elasticsearch --elasticsearch-docker-image=elasticsearch:7.17.14
    fi
fi

echo "👷 Configured search engine: $SEARCH_ENGINE"

echo "✅ Finished setting up ddev services. Restarting the environment..."
echo "`date`" > "$PROVISION_FILE_SERVICES"
verbose_output ddev restart -y
