#!/bin/bash

## #ddev-generated
## Description: Runs interactive installer for Ibexa DXP
## Usage: ibexa-installer
## Example: ddev ibexa-installer

source .ddev/commands/host/.utils

if [ -f "$IBEXA_DXP_INSTALLED_LOCK_FILE" ] || [ ! -f "$INSTANCE_SETTINGS_FILE" ]
then
  # Nothing to do
  echo "Nothing to do $IBEXA_DXP_INSTALLED_LOCK_FILE"
  exit 0
fi

source "$INSTANCE_SETTINGS_FILE"

#
# Default settings
#

ADMIN_USERNAME=admin
ADMIN_PASSWORD=publish

#
# Main
#

function composer_auth_error() {
    echo "❗️ Cannot access `(faint updates.ibexa.co)`"
    echo "Please provide your composer auth details to ddev and re-run `(faint "ddev start")`. The process will continue using previously configured settings."
    exit 1
}

if [ "$VERBOSE_INSTALL" == false ]; then
    clear
fi

# Fallback headless -> content for 3.3 releases
if [[ "$PRODUCT_VERSION" == *"3.3."* && "$DXP_EDITION" == "headless" ]]; then
    PRODUCT_TYPE="Ibexa DXP Content"
    DXP_EDITION=content
fi

# Workaround to the issue on Mac OS
ddev exec git config --global --add safe.directory /var/www/html

banner "Interactive Installation Tool"

echo "🚀 Product to be installed: `(bold "$PRODUCT_TYPE $PRODUCT_VERSION")`"

# Installation steps depend on project

# 1. Existing project / with all vendor files
if [ -d vendor ]; then
    REQUIRE=NONE
    INSTALL_PROFILER=false
    INSTALL_CLOUD_CONFIG=false
    INSTALL_SAMPLE_DATA=false
# 2. Existing project / no vendor files
elif [ -f composer.lock ]; then
    REQUIRE=NONE
    if [ "$APP_ENV" == "dev" ]; then
      execute_with_spinner "Running Composer [install]" composer install --optimize-autoloader
    else
      execute_with_spinner "Running Composer [install]" composer install --no-dev --optimize-autoloader
    fi
    echo "✅ Package `(bold ibexa/${DXP_EDITION})` installed successfully"
# 3. New DEV Installation
elif [[ "$PRODUCT_VERSION" =~ .*"-dev" ]]; then
    mv .env.local .ddev/.env.local
    ddev composer create-project ibexa/website-skeleton:$PRODUCT_VERSION
    ddev composer config repositories.ibexa composer https://updates.ibexa.co
    if [[ "$PRODUCT_VERSION" = *"4.6"* ]]; then
        ddev composer config extra.runtime.error_handler "\\Ibexa\\Contracts\\Core\\MVC\\Symfony\\ErrorHandler\\Php82HideDeprecationsErrorHandler"
    fi

    if [ "$DXP_EDITION" != "oss" ]; then
        trap 'composer_auth_error' ERR
        execute_with_spinner "Checking `(bold updates.ibexa.co)` authorization" composer require ibexa/$DXP_EDITION:$PRODUCT_VERSION -W --no-scripts --no-plugins --no-install --no-interaction --quiet
        trap 'error_handler' ERR
        echo "✅ Repository `(bold updates.ibexa.co)` is reachable"
    fi
    execute_with_spinner "Composer require ibexa/${DXP_EDITION}:${PRODUCT_VERSION}" composer require ibexa/$DXP_EDITION:$PRODUCT_VERSION -W --no-scripts --no-interaction
    
    ddev exec git init -q > /dev/null; ddev exec git add . :'!.ddev' > /dev/null; ddev exec git commit -m "Installed Ibexa DXP" > /dev/null;
    echo "✅ Initialized git repository"
    
    ddev composer recipes:install ibexa/$DXP_EDITION --force --reset
    echo "✅ Package `(bold ibexa/${DXP_EDITION})` installed successfully"
    
    ddev exec git add . :'!.ddev' > /dev/null;
    ddev exec 'if [ $(git diff --cached --numstat | wc -l) -ne 0 ]; then git commit -m "recipes:install" > /dev/null; fi'
    echo "✅ recipes:install done"
    mv .ddev/.env.local .env.local
# 4. New regular release
else
    mv .env.local .ddev/.env.local
    ddev composer create-project -y ibexa/$DXP_EDITION-skeleton:$PRODUCT_VERSION --no-install
    
    if [[ "$PHP_VERSION" = "8.3" && ( "$PRODUCT_VERSION" =~ ^(~|v)?(5|6)\.0  || "$PRODUCT_VERSION" =~ ^(~|v)?4\.6 )  ]]; then
        COMPOSER_MODE=install
        REQUIRE_MODE="--no-scripts --no-plugins --no-install --no-interaction --quiet"
    else
        COMPOSER_MODE=update
        REQUIRE_MODE="--update-with-all-dependencies --no-scripts --no-plugins --no-install --no-interaction --quiet"
    fi

    if [ "$DXP_EDITION" != "oss" ]; then
        trap 'composer_auth_error' ERR
        execute_with_spinner "Checking `(bold updates.ibexa.co)` authorization" composer require ibexa/$DXP_EDITION:$PRODUCT_VERSION $REQUIRE_MODE
        trap 'error_handler' ERR
        echo "✅ Repository `(bold updates.ibexa.co)` is reachable"
    fi

    execute_with_spinner "Running Composer [$COMPOSER_MODE]" composer $COMPOSER_MODE --optimize-autoloader

    echo "✅ Package `(bold ibexa/${DXP_EDITION})` installed successfully"
    ddev exec git init -q  > /dev/null; ddev exec git add . :'!.ddev' > /dev/null; ddev exec git commit -m "Installed Ibexa DXP" > /dev/null;
    echo "✅ Initialized git repository"
    mv .ddev/.env.local .env.local
fi

# read vcl from vendor/ibexa/hhtp-cache
if [ "$HTTP_CACHE" == "varnish" ]; then
    ddev ibexa-syncvcl 
fi

ADDED_PACKAGE=false
# Install test fixtures
if [[ "$INSTALL_SAMPLE_DATA" == true && "$PRODUCT_VERSION" != *"3.3"* ]]; then
    if [[ "$PRODUCT_VERSION" = *"4.6"* ]]; then
        FIXTURES_VERSION=~4.6.x-dev
    elif [[ "$PRODUCT_VERSION" = *"6.0"* ]]; then
        FIXTURES_VERSION=~6.0.x-dev
    else
        FIXTURES_VERSION=~5.0.x-dev
    fi
    
    if [ "$?" == 0 ]; then
        execute_with_spinner "Require [ibexa/test-fixtures]" composer require ibexa/test-fixtures:$FIXTURES_VERSION --no-scripts --no-interaction
        echo "✅ Installed ibexa/test-fixtures package"
        ADDED_PACKAGE=true
    else
        echo "⚠️ `(bold "ibexa/test-fixtures")` package is unavailable. Cannot install sample data."
    fi

fi

# Install profiler
if [ "$INSTALL_PROFILER" == true ]; then
    execute_with_spinner "Require [symfony/profiler-pack]" composer require --dev symfony/profiler-pack --no-scripts --no-interaction
    echo "✅ Installed Symfony Profiler"
    ADDED_PACKAGE=true
fi

# Setup Ibexa Cloud
if [ "$INSTALL_CLOUD_CONFIG" == true ]; then
    if [ "$CLOUD_CONFIG" == "upsun" ]; then
      execute_with_spinner "Setup Ibexa Cloud [require ibexa/cloud]" composer require ibexa/cloud
      execute_with_spinner "Setup Ibexa Cloud [php bin/console ibexa:cloud:setup]" php bin/console ibexa:cloud:setup --upsun
    else
      execute_with_spinner "Setup Ibexa Cloud [ibexa:setup --platformsh]" composer ibexa:setup --platformsh
    fi
    echo "✅ Installed Ibexa Cloud configuration"
    ADDED_PACKAGE=true
fi

if [[ "$ADDED_PACKAGE" == true &&  ! "$REQUIRE" == "NONE" ]]; then
  ddev exec git add . :'!.ddev' > /dev/null; ddev exec git commit -m "Added packages" &> /dev/null;
fi

echo "✅ Scripts finished successfully"

if [[ "$PRODUCT_VERSION" =~ .*"-dev" ]]; then
    execute_with_spinner "Composer [post-update-cmd]" composer run post-update-cmd
    execute_with_spinner "Install DB [ibexa:install]" php bin/console ibexa:install --quiet --no-debug --skip-indexing --no-interaction
    ddev php bin/console cache:clear
    if [ "$APP_CACHE" == "redis" ]; then
      ddev php bin/console cache:pool:clear cache.redis
    fi
else
    execute_with_spinner "Install DB [ibexa:install]" php bin/console ibexa:install --quiet --no-debug --skip-indexing --no-interaction
fi
echo "✅ Database installed"

if [ "$SEARCH_ENGINE" = "elasticsearch" ]; then
    if [[ "$SEARCH_ENGINE" == "elasticsearch8" && "$PRODUCT_VERSION" = *"4.6"* ]]; then
      execute_with_spinner "Require elasticsearch8 for v4.6" composer require ibexa/elasticsearch8 --with-all-dependencies
    fi
    # clear elastic index before creating index template
    ddev exec  curl -XDELETE 'elasticsearch:9200/*' > /dev/null
    ddev php bin/console ibexa:elasticsearch:put-index-template
    echo "✅ Put Elasticsearch index template"
fi

if [ "$SEARCH_ENGINE" = "solr" ]; then
    mkdir .ddev/solr/configsets/collection1
    chmod 777 .ddev/solr/configsets/collection1
    cp -R vendor/ibexa/solr/src/lib/Resources/config/solr/* .ddev/solr/configsets/collection1/

    ddev exec -s solr cp -R /opt/solr/server/solr/configsets/_default/conf/{solrconfig.xml,stopwords.txt,synonyms.txt} /mnt/ddev_config/solr/configsets/collection1/

    ddev solr-zk upconfig -n collection1 -d /mnt/ddev_config/solr/configsets/collection1 -z localhost:9983
    ddev exec -s solr solr create -c collection1 -n collection1 -shards 1 -replicationFactor 1
    # set env var
    echo "SEARCH_ENGINE=solr" >> .env.local

    echo "✅ Created Solr Collection"
fi

execute_with_spinner "Reindex [ibexa:reindex]" php bin/console ibexa:reindex
echo "✅ Reindexed search data"

function sample_data_error() {
    echo "❗️ Error while creating sampea data ❗️"
}

# Setup sample data
if [ "$INSTALL_SAMPLE_DATA" == true ]; then
    trap 'sample_data_error' ERR
    execute_with_spinner " [ibexa:test-fixtures:setup]" php bin/console ibexa:test-fixtures:setup --quiet
    trap 'error_handler' ERR
    echo "✅ Installed sample data"
fi

execute_with_spinner "Generate GraphQL schema [ibexa:graphql:generate-schema]" php bin/console ibexa:graphql:generate-schema
echo "✅ GraphQL schema generated"

if [[ "$REQUIRE" == "NONE" ]]; then
  execute_with_spinner "Composer [post-update-cmd]" composer run post-update-cmd
fi


echo "✅ All done! You can now access your new project using provided details:"

ddev gum style --border double --margin "1 1" --padding "1 1" --width 60 \
    "Website:        ` bold --bold "$DDEV_PRIMARY_URL" `" \
    "Backoffice:     ` bold --bold "$DDEV_PRIMARY_URL/admin" `" \
    "" \
    "Username:       ` bold "admin" `" \
    "Password:       ` bold "publish" `" \
    "" \
    "Run `(bold "ddev describe")` for more details"

echo "📧  Run `(bold "ddev mailpit")` to launch Mailpit interface and see caught e-mails"
echo "🗄️   Run `(bold "ddev add-on  get ddev/ddev-phpmyadmin")` to install PHPMyAdmin"
echo "🗄️   Run `(bold "ddev querious|sequelace|tableplus|dbeaver")` to launch database client app"
echo ""
echo "📦️  Run `(bold "ddev composer ...")` to execute Composer commands"
echo "🐘️  Run `(bold "ddev php ...")` to execute PHP scripts"
echo "🐞️  Run `(bold "ddev xdebug on|off")` to control Xdebug"
echo ""
echo "🚀️  Run `(bold "ddev start")` to start containers"
echo "⛔️  Run `(bold "ddev stop")` to stop containers"
echo "🔄️  Run `(bold "ddev restart")` to restart containers"

echo "`date`" > ./.ddev/.ibexa-dxp-installed
