#!/bin/bash

## #ddev-generated
## Description: Runs service configurator
## Usage: ibexa-configurator
## Example: ddev ibexa-configurator

source .ddev/commands/web/.utils

#
# Default settings
#

LABEL_INSTALL_SAMPLE_DATA="Yes"
LABEL_INSTALL_PROFILER="Yes"
IBEXA_DXP_PRODUCTS=("oss" "headless" "experience" "commerce")

[ -z "$PHP_VERSION" ] && PHP_VERSION="8.3"
[ -z "$DATABASE" ] && DATABASE="mariadb"
[ -z "$DATABASE_VERSION" ] && DATABASE_VERSION="10.11"
[ -z "$NODE_VERSION" ] && NODE_VERSION="22"
[ -z "$HTTP_CACHE" ] && HTTP_CACHE="symfony"
[ -z "$HTTP_SERVER" ] && HTTP_SERVER="nginx-fpm"
[ -z "$APP_CACHE" ] && APP_CACHE="redis"
[ -z "$SEARCH_ENGINE" ] && SEARCH_ENGINE="legacy"
[ -z "$INSTALL_SAMPLE_DATA" ] && INSTALL_SAMPLE_DATA=false
[ -z "$INSTALL_PROFILER" ] && INSTALL_PROFILER=true
[ -z "$APP_ENV" ] && APP_ENV="dev"
[ -z "$INSTALL_CLOUD_CONFIG" ] && INSTALL_CLOUD_CONFIG=true
[ -z "$CLOUD_CONFIG" ] && CLOUD_CONFIG="upsun"
[ -z "$PLATFORM_APP" ] && PLATFORM_APP=false

if [ -f "$INSTANCE_SETTINGS_FILE" ]; then
    # Nothing to do
    exit 0
fi

function detect_installation() {
    if [ -f composer.lock ]; then
        REQUIRE=NONE
        # profiler loaded from composer.json
        INSTALL_PROFILER=false
        LABEL_INSTALL_PROFILER="No"
        # fixtures loaded from composer.json
        INSTALL_SAMPLE_DATA=false
        LABEL_INSTALL_SAMPLE_DATA="No"
        #
        INSTALL_CLOUD_CONFIG=false
    fi
}

function detect_version() {
    if [ "$DXP_EDITION" != "website" ] && [ -f composer.lock ]; then
        MIN_STABILITY="`(jq -r '."minimum-stability"' composer.lock)`"
        PRODUCT_VERSION="`(jq -r '.packages[] | select(.name == "ibexa/oss") | .version' composer.lock | sed 's/^v//')`"
    elif [ -f composer.json ]; then
        MIN_STABILITY="`(jq -r '."minimum-stability"' composer.json)`"
        PRODUCT_VERSION="`(jq -r '.extra."branch-alias"."dev-main"' composer.json)`"
    elif [[ ! "$PRODUCT_VERSION" =~ .*"-dev" ]]; then
        PRODUCT_VERSION="5.0"
        MIN_STABILITY="dev"
        DXP_EDITION="website"
    fi
}

function detect_product() {
    if [ ! "$REQUIRE" == "NONE" ]; then
        PRODUCT_TYPE="Ibexa DXP Experience"
        return
    fi

    PROJECT_NAME=$(jq -r '.name' composer.json)
    # try to extract prouct edition from composer.json -> require
    if [ "$PROJECT_NAME" == "null" ] ||  \
       [ "$PROJECT_NAME" == "ibexa/website-skeleton" ] && \
       [ "$(jq  -r '.require | to_entries[] | select(.key | startswith("ibexa/"))' composer.json)" != "" ]; then
        PROJECT_NAME=$(jq  -r '.require | to_entries[] | select(.key | startswith("ibexa/commerce") or startswith("ibexa/experience") or startswith("ibexa/headless") or startswith("ibexa/content")) | .key ' composer.json)
    fi

    # Strip "ibexa/" and "-skeleton" parts from the value
    DXP_EDITION=$(echo $PROJECT_NAME | sed 's/ibexa\///;s/-skeleton//')
    case "$DXP_EDITION" in
        "commerce")
            PRODUCT_TYPE="Ibexa DXP Commerce"
            ;;
        "experience")
            PRODUCT_TYPE="Ibexa DXP Experience"
            ;;
        "headless")
            PRODUCT_TYPE="Ibexa DXP Headless"
            ;;
        "oss")
            PRODUCT_TYPE="Ibexa OSS"
            ;;
        "content")
            PRODUCT_TYPE="Ibexa Content (3.3 & <=4.5)"
            ;;
    esac
}

function configure_product() {
    if [ "$REQUIRE" == "NONE" ]; then
      return
    fi

    if [ "$DXP_EDITION" = "website" ]; then
        choose "`(faint "[Product]")` `(bold "Select Ibexa product")`" "Ibexa OSS" "Ibexa DXP Headless" "Ibexa DXP Experience" "Ibexa DXP Commerce"
        PRODUCT_TYPE="$SELECT"
        case "$SELECT" in
            "Ibexa DXP Commerce")
                DXP_EDITION=commerce
                ;;
            "Ibexa DXP Experience")
                DXP_EDITION=experience
                ;;
            "Ibexa DXP Headless")
                DXP_EDITION=headless
                ;;
            "Ibexa OSS")
                DXP_EDITION=oss
                ;;
        esac
    fi

    if [ "$PRODUCT_VERSION" == "5.0" ]; then
        PRODUCT_VERSION=~5.0.0
    elif [ "$PRODUCT_VERSION" == "4.6 Latest" ]; then
        PRODUCT_VERSION=~4.6.0
    fi
}

function configure_release() {
    if [ "$REQUIRE" == "NONE" ]; then
        return
    fi

    choose_delimited "`(faint "[Release]")` `(bold "Select Release")`" "$PRODUCT_VERSION" "5.0 LTS:~5.0.0" "5.0.x dev:~5.0.x-dev" "5.0.x release:5.0.x release" "4.6 LTS:~4.6.0" "4.6.x dev:~4.6.x-dev" "4.6.x release:4.6.x release" "3.3 LTS:~3.3.0" "3.3.x release:3.3.x release"
    if [[ "$SELECT" =~ .*"x release" ]]; then
        PRODUCT_VERSION=$SELECT
        PRODUCT_VERSION="${SELECT/x release/}"
        PRODUCT_VERSION=$(gum input --value=$PRODUCT_VERSION --prompt="Please provide minor release >  ")
    else
        PRODUCT_VERSION="$SELECT"
    fi
}

function configure_php() {
    if [[ "$PRODUCT_VERSION" =~ ^(~|v)?5\.0\. ]]; then
        PHP_VERSION="8.3"
        return
    fi

    if [[ "$PRODUCT_VERSION" == *"3.3."* ]]; then
      choose_delimited "`(faint "[Setup]")` `(bold "Select PHP version")`" "$PHP_VERSION" "8.3 (recommended):8.3" "8.2:8.2" "8.1:8.1" "7.4:7.4"
    else
      choose_delimited "`(faint "[Setup]")` `(bold "Select PHP version")`" "$PHP_VERSION" "8.3 (recommended):8.3" "8.2:8.2" "8.1:8.1"
    fi
    PHP_VERSION="$SELECT"
}

function configure_node() {
    if [[ "$PRODUCT_VERSION" =~ ^(~|v)?5\.0\. ]]; then
        NODE_VERSION="22"
        return
    fi

    choose_delimited "`(faint "[Setup]")` `(bold "Select Node version")`" "$NODE_VERSION" "20 (recommended):20" "18:18" "21:21" "22:22"
    NODE_VERSION="$SELECT"
}

function configure_http_server() {
    choose_delimited "`(faint "[Setup]")` `(bold "Select HTTP server")`" "$HTTP_SERVER" "nginx (recommended):nginx-fpm" "Apache:apache-fpm"
    HTTP_SERVER="$SELECT"
}

function configure_http_cache() {
    choose_delimited "`(faint "[Setup]")` `(bold "Select HTTP cache")`" "$HTTP_CACHE" "Symfony:symfony" "Varnish (recommended):varnish"
    HTTP_CACHE="$SELECT"
}

function configure_database() {
    choose_delimited "`(faint "[Setup]")` `(bold "Select database platform")`" "$DATABASE" "MariaDB (recommended):mariadb" "MySQL:mysql" "PostgreSQL:postgres"
    case "$SELECT" in
        "mariadb")
            DATABASE="mariadb"
            configure_mariadb_version
            ;;
        "mysql")
            DATABASE="mysql"
            configure_mysql_version
            ;;
        "postgres")
            DATABASE="postgres"
            configure_postgres_version
            ;;
    esac
}

function configure_mariadb_version() {
    if [[ "$PRODUCT_VERSION" =~ ^(~|v)?5\.0\. ]]; then
        DATABASE_VERSION="10.11"
        return
    fi

    choose_delimited "`(faint "[Setup]")` `(bold "Select MariaDB version")`" "$DATABASE_VERSION" "10.11 (recommended):10.11" "10.4:10.4" "10.3:10.3"
    DATABASE_VERSION="$SELECT"
}

function configure_mysql_version() {
    if [[ "$PRODUCT_VERSION" =~ ^(~|v)?5\.0\. ]]; then
        DATABASE_VERSION="8.4"
        return
    fi

    if [[ "$PRODUCT_VERSION" == *"3.3."* ]]; then
        choose_delimited "`(faint "[Setup]")` `(bold "Select Mysql version")`" "$DATABASE_VERSION" "8.0 (recommended):8.0" "5.7:5.7"
    else
        choose_delimited "`(faint "[Setup]")` `(bold "Select Mysql version")`" "$DATABASE_VERSION" "8.4 (recommended):8.4" "8.0:8.0"
    fi
    DATABASE_VERSION="$SELECT"
}

function configure_postgres_version() {
    choose_delimited "`(faint "[Setup]")` `(bold "Select PostgreSQL version")`" "$DATABASE_VERSION" "16 (recommended):16" "15:15" "14:14" "13:13" "12:12" "11:11" "10:10"
    DATABASE_VERSION="$SELECT"
}

function configure_app_cache() {
    choose_delimited "`(faint "[Setup]")` `(bold "Select application cache")`" "$APP_CACHE" "Redis (recommended):redis" "Memcached:memcached" "Filesystem:filesystem"
    APP_CACHE="$SELECT"
}

function configure_search_engine() {
    if [ "$DXP_EDITION" != "oss" ]; then
        choose_delimited "`(faint "[Setup]")` `(bold "Select search engine")`" "$SEARCH_ENGINE" "Legacy:legacy" "Elasticsearch (recommended):elasticsearch" "Solr:solr"
    else
        choose_delimited "`(faint "[Setup]")` `(bold "Select search engine")`" "$SEARCH_ENGINE" "Legacy:legacy" "Solr (recommended):solr"
    fi

    SEARCH_ENGINE="$SELECT"
}

function configure_sample_data() {
    if [ "$REQUIRE" == "NONE" ]; then
        return
    fi

    # skip for 5.0 tagged releases
    if [[ "$PRODUCT_VERSION" =~ ^(~|v)?5\.0\. && ! "$PRODUCT_VERSION" =~ .*"-dev" ]]; then
        return
    fi

    if [ "$DXP_EDITION" != "oss" ]; then
        choose "`(faint "[Instance]")` `(bold "Install sample data?")`" "No" "Yes"
        case "$SELECT" in
            "No")
                INSTALL_SAMPLE_DATA=false
                LABEL_INSTALL_SAMPLE_DATA="No"
                ;;
            "Yes")
                INSTALL_SAMPLE_DATA=true
                LABEL_INSTALL_SAMPLE_DATA="Yes"
                ;;
        esac
    else
        # OSS is incompatible with ibexa/test-fixtures
        INSTALL_SAMPLE_DATA=false
        LABEL_INSTALL_SAMPLE_DATA="No"
    fi
}

function configure_profiler() {
    if [ "$REQUIRE" == "NONE" ]; then
        return
    fi

    choose "`(faint "[Instance]")` `(bold "Install Symfony profiler?")`" "Yes" "No"
    case "$SELECT" in
        "Yes")
            INSTALL_PROFILER=true
            LABEL_INSTALL_PROFILER="Yes"
            ;;
        "No")
            INSTALL_PROFILER=false
            LABEL_INSTALL_PROFILER="No"
            ;;
    esac
}

function configure_app_env() {
    choose "`(faint "[Instance]")` `(bold "Select app environment")`" "prod (recommended)" "dev"
    case "$SELECT" in
        "prod (recommended)")
            APP_ENV=prod
            ;;
        "dev")
            APP_ENV=dev
            ;;
    esac
}

function configure_cloud() {
    if [ "$REQUIRE" == "NONE" ]; then
        return
    fi

    if [[ "$PRODUCT_VERSION" =~ ^~5\.0\. || "$PRODUCT_VERSION" =~ ^(v)?5\.0\.([x6-9]|[1-9][0-9]+) ]]; then
        CLOUD_CONFIG="upsun"
    else
        CLOUD_CONFIG="platformsh"
    fi

    choose "`(faint "[Instance]")` `(bold "Install Ibexa Cloud configuration?")`" "Yes (recommended)" "No"
    case "$SELECT" in
        "Yes (recommended)")
            INSTALL_CLOUD_CONFIG=true
            ;;
        "No")
            INSTALL_CLOUD_CONFIG=false
            ;;
    esac
}

function format_bool() {
    if [ "$1" == true ]; then
        echo "yes"
    else
        echo "no"
    fi
}

function info_table() {
    gum style \
        --border double \
        --align center --margin "0" --padding "1 2" \
        "$@"
}

function print_selected_settings() {
    echo "${1}" # print title

    TABLE_APPLICATION=$(info_table "`(bold Application)`" \
        "" \
        "`(faint "Product:")` `(bold "$PRODUCT_TYPE")`" \
        "`(faint "Version:")` `(bold "$PRODUCT_VERSION")`" \
        "")

    TABLE_SERVICES=$(info_table --border-foreground "#F4B19B" "`(bold Services)`" \
        "" \
        "`(faint "HTTP Cache:")` `(bold "$HTTP_CACHE")`" \
        "`(faint "App Cache:")` `(bold "$APP_CACHE")`" \
        "`(faint "Search Engine:")` `(bold "$SEARCH_ENGINE")`")

    TABLE_ENVIRONMENT=$(info_table --border-foreground "#FFE6D7" "`(bold Environment)`" \
        "" \
        "`(faint "Web Server:")` `(bold "$HTTP_SERVER")`" \
        "`(faint "PHP:")` `(bold "$PHP_VERSION")`" \
        "`(faint "Node:")` `(bold "$NODE_VERSION")`" \
        "`(faint "Database:")` `(bold "$DATABASE")` `(faint "("$DATABASE_VERSION")")`")

    TABLE_EXTRAS=$(info_table --border-foreground "#78B1E0" "`(bold Extras)`" \
        "" \
        "`(faint "Install sample data:")` `(bold $(format_bool "$INSTALL_SAMPLE_DATA"))`" \
        "`(faint "Install Ibexa Cloud config:")` `(bold $(format_bool "$INSTALL_CLOUD_CONFIG"))`" \
        "`(faint "Install Symfony Profiler:")` `(bold $(format_bool "$INSTALL_PROFILER"))`" \
        "`(faint "App environment:")` `(bold "$APP_ENV")`")

    ROW_1=$(gum join "$TABLE_APPLICATION" "$TABLE_SERVICES")
    ROW_2=$(gum join "$TABLE_ENVIRONMENT" "$TABLE_EXTRAS")
    gum join --align center --vertical "$ROW_1" "$ROW_2"
    echo ""
}

function select_configuration() {
    configure_release
    configure_php
    configure_node
    configure_http_server
    configure_database
    configure_http_cache
    configure_app_cache
    configure_search_engine
    configure_sample_data
    configure_profiler
    configure_app_env
    configure_cloud

    print_selected_settings "`gum style --bold --underline -- "Your configuration:"`"

    if ! gum confirm "Confirm these settings?" ;
    then
        select_configuration
    fi
}

function save_settings_file() {
    {
        declare -p DXP_EDITION
        declare -p PRODUCT_TYPE
        declare -p PRODUCT_VERSION
        declare -p PHP_VERSION
        declare -p NODE_VERSION
        declare -p DATABASE
        declare -p DATABASE_VERSION
        declare -p HTTP_CACHE
        declare -p APP_CACHE
        declare -p SEARCH_ENGINE
        declare -p INSTALL_SAMPLE_DATA
        declare -p INSTALL_PROFILER
        declare -p APP_ENV
        declare -p HTTP_SERVER
        declare -p INSTALL_CLOUD_CONFIG
        declare -p CLOUD_CONFIG

    } > "$INSTANCE_SETTINGS_FILE"
}

#
# Main
#

clear

banner "Interactive Installation Tool"

bold "⚠️  This tool is experimental. Do not use on production servers."
echo ""

detect_installation
detect_product
detect_version

configure_product

if [ "$PLATFORM_APP" == true ]; then
  print_selected_settings "`gum style --bold --underline -- "Configuration with presets from Ibexa Cloud .platform.app.yaml:"`"
else
  print_selected_settings "`gum style --bold --underline -- "Recommended configuration:"`"
fi


if ! gum confirm "Do you confirm these settings?" ;
then
    select_configuration
fi

save_settings_file
